---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: User
  labels:
    app: User
spec:
  replicas: 1
  selector:
    matchLabels:
      app: User
  template:
    metadata:
      labels:
        app: User
    spec:
      containers:
        - name: User
          image: username/User:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Food_Store
  labels:
    app: Food_Store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Food_Store
  template:
    metadata:
      labels:
        app: Food_Store
    spec:
      containers:
        - name: Food_Store
          image: username/Food_Store:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Rider
  labels:
    app: Rider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Rider
  template:
    metadata:
      labels:
        app: Rider
    spec:
      containers:
        - name: Rider
          image: username/Rider:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: User
  labels:
    app: User
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: User


---


apiVersion: v1
kind: Service
metadata:
  name: Food_Store
  labels:
    app: Food_Store
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Food_Store


---


apiVersion: v1
kind: Service
metadata:
  name: Rider
  labels:
    app: Rider
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Rider

